### ISSUE TITLE
RuntimeError: "sum_cuda" not implemented for 'Bool'

### ISSUE THREAD

**Issue by yuanzhiroc** [svjan5/GNNs-for-NLP#2]
```
ubuntu@f6b86bb5112d:~/GNNs-for-NLP$ python pytorch_gcn.py
2019-11-19 11:50:03,447 - [INFO] - {'data': 'cora', 'gpu': '0', 'name': 'test_19_11_2019_11:50:03', 'lr': 0.01, 'max_epochs':200, 'l2': 0.0005, 'seed': 1234, 'opt': 'adam', 'gcn_dim': 16, 'dropout': 0.5, 'restore': False, 'log_dir': './log/', 'config_dir': './config/', 'model_dir': './models/', 'save_dir': './models//test_19_11_2019_11:50:03'}
{'config_dir': './config/',
 'data': 'cora',
 'dropout': 0.5,
 'gcn_dim': 16,
 'gpu': '0',
 'l2': 0.0005,
 'log_dir': './log/',
 'lr': 0.01,
 'max_epochs': 200,
 'model_dir': './models/',
 'name': 'test_19_11_2019_11:50:03',
 'opt': 'adam',
 'restore': False,
 'save_dir': './models//test_19_11_2019_11:50:03',
 'seed': 1234}
loading data
Traceback (most recent call last):
  File "pytorch_gcn.py", line 248, in <module>
    model.fit()
  File "pytorch_gcn.py", line 208, in fit
    train_loss = self.run_epoch(epoch)
  File "pytorch_gcn.py", line 175, in run_epoch
    train_acc   = self.get_acc(logits[self.data.train_mask], self.data.y, self.data.train_mask)
  File "pytorch_gcn.py", line 122, in get_acc
    return y_pred.eq(y_actual[mask]).sum().item() / mask.sum().item()
RuntimeError: "sum_cuda" not implemented for 'Bool'
```
python3.6
pytorch1.1
Is the pytorch version lower?

**Comment by svjan5** [comment]
Hi @yuanzhiroc,
On the shared [colab](https://colab.research.google.com/drive/1HOV56wSuVd9mzBDa43dua4oKuNw1kMPP#scrollTo=w7qrBnRf8Ue9) the given code works. Seems like the pytorch-geometric library is not installed properly in your case.
